// Foundry names in the typeface files don't match the bookmark titles in
// data/foundries.json ("Klim Type Foundry" vs "Klim Type Foundry - Home"),
// so homepage URLs and tiers are pinned here for the 13 indexed foundries.

export type FoundryInfo = {
  name: string; // as it appears in the typeface files
  slug: string;
  homepage: string;
  tier: "best" | "good" | "okay" | "notgood";
};

export const FOUNDRIES: FoundryInfo[] = [
  { name: "atipo foundry", slug: "atipo-foundry", homepage: "https://www.atipofoundry.com/", tier: "best" },
  { name: "Commercial Type", slug: "commercial-type", homepage: "https://commercialtype.com/", tier: "okay" },
  { name: "Dalton Maag", slug: "dalton-maag", homepage: "https://www.daltonmaag.com/", tier: "best" },
  { name: "Dinamo Typefaces", slug: "dinamo-typefaces", homepage: "https://abcdinamo.com/", tier: "best" },
  { name: "Displaay Type Foundry", slug: "displaay-type-foundry", homepage: "https://displaay.net/", tier: "best" },
  { name: "F37 Foundry", slug: "f37-foundry", homepage: "https://www.f37foundry.com/", tier: "okay" },
  { name: "Grilli Type", slug: "grilli-type", homepage: "https://www.grillitype.com/", tier: "best" },
  { name: "Hoefler & Co", slug: "hoefler-co", homepage: "https://www.typography.com/", tier: "notgood" },
  { name: "Klim Type Foundry", slug: "klim-type-foundry", homepage: "https://klim.co.nz/", tier: "best" },
  { name: "Optimo", slug: "optimo", homepage: "https://optimo.ch/", tier: "best" },
  { name: "Pangram Pangram Foundry", slug: "pangram-pangram-foundry", homepage: "https://pangrampangram.com/", tier: "best" },
  { name: "Schick Toikka", slug: "schick-toikka", homepage: "https://www.schick-toikka.com/", tier: "best" },
  { name: "Sociotype", slug: "sociotype", homepage: "https://socio-type.com/", tier: "best" },
  { name: "Lineto", slug: "lineto", homepage: "https://lineto.com/", tier: "best" },
  { name: "Swiss Typefaces", slug: "swiss-typefaces", homepage: "https://www.swisstypefaces.com/", tier: "best" },
  { name: "Production Type", slug: "production-type", homepage: "https://www.productiontype.com/", tier: "best" },
  { name: "Newlyn", slug: "newlyn", homepage: "https://newlyn.com/", tier: "best" },
  { name: "Typotheque", slug: "typotheque", homepage: "https://www.typotheque.com/", tier: "best" },
  { name: "OH no Type", slug: "oh-no-type", homepage: "https://ohnotype.co/", tier: "best" },
  { name: "Fontwerk", slug: "fontwerk", homepage: "https://fontwerk.com/", tier: "best" },
  { name: "CAST", slug: "cast", homepage: "https://www.c-a-s-t.com/", tier: "best" },
  { name: "Camelot", slug: "camelot", homepage: "https://camelot-typefaces.com/", tier: "best" },
  { name: "Extraset", slug: "extraset", homepage: "https://extraset.ch/", tier: "best" },
  { name: "Fatype", slug: "fatype", homepage: "https://fatype.com/", tier: "best" },
  { name: "NaN", slug: "nan", homepage: "https://www.nan.xyz/", tier: "best" },
  { name: "Signal", slug: "signal", homepage: "https://signalfoundry.com/", tier: "best" },
  { name: "Blaze Type", slug: "blaze-type", homepage: "https://blazetype.eu/", tier: "best" },
  { name: "a.Foundry", slug: "a-foundry", homepage: "https://a-foundry.com/", tier: "best" },
  { name: "AllCaps", slug: "allcaps", homepage: "https://www.allcapstype.com/", tier: "best" },
  { name: "Arillatype", slug: "arillatype", homepage: "https://arillatype.studio/", tier: "best" },
  { name: "Faire Type", slug: "faire-type", homepage: "https://www.fairetype.com/", tier: "best" },
  { name: "British Standard Type", slug: "british-standard-type", homepage: "https://www.britishstandardtype.xyz/", tier: "best" },
  { name: "OTT Foundry", slug: "ott-foundry", homepage: "https://ott-foundry.com/", tier: "best" },
  { name: "Bureau Brut", slug: "bureau-brut", homepage: "https://bureaubrut.com/", tier: "best" },
  { name: "A Type of Amigo", slug: "a-type-of-amigo", homepage: "https://atypeofamigo.com/", tier: "best" },
  { name: "Bastarda", slug: "bastarda", homepage: "https://bastardatype.com/", tier: "best" },
  { name: "Interval Type", slug: "interval-type", homepage: "https://intervaltype.com/", tier: "best" },
  { name: "Due Studio", slug: "due-studio", homepage: "https://www.due-studio.com/", tier: "best" },
  { name: "Typespec", slug: "typespec", homepage: "https://typespec.co.uk/", tier: "best" },
  { name: "Almarena", slug: "almarena", homepage: "https://almarenafoundry.com/", tier: "best" },
  { name: "A2-Type", slug: "a2-type", homepage: "https://a2-type.co.uk/", tier: "best" },
  { name: "Binnenland", slug: "binnenland", homepage: "https://www.binnenland.ch/", tier: "best" },
  { name: "Florian Karsten", slug: "catalogue", homepage: "https://fonts.floriankarsten.com/", tier: "best" },
  { name: "Frost", slug: "frost", homepage: "https://frostype.xyz/", tier: "best" },
  { name: "Groteskly Yours", slug: "groteskly-yours", homepage: "https://groteskly.xyz/", tier: "best" },
  { name: "General Type Studio", slug: "general-type-studio", homepage: "https://www.generaltypestudio.com/", tier: "best" },
  { name: "Leinster Type", slug: "leinster-type", homepage: "https://www.leinstertype.com/", tier: "best" },
  { name: "Playtype", slug: "playtype", homepage: "https://playtype.com/", tier: "best" },
  { name: "Studio Rene Bieder", slug: "studio-rene-bieder", homepage: "https://www.renebieder.com/", tier: "best" },
  { name: "The Designers Foundry", slug: "the-designers-foundry", homepage: "https://thedesignersfoundry.com/", tier: "best" },
  { name: "Prioritype", slug: "prioritype", homepage: "https://prioritypeco.com/", tier: "best" },
  { name: "Taylor Penton", slug: "taylor-penton", homepage: "https://www.taylorpenton.com/", tier: "best" },
  { name: "VJ Type", slug: "vj-type", homepage: "https://vj-type.com/", tier: "best" },
  { name: "Balto / Type Supply", slug: "balto-type-supply", homepage: "https://typesupply.com/", tier: "okay" },
  { name: "Big Fog Foundry", slug: "big-fog-foundry", homepage: "https://foundry.bigfog.co/", tier: "okay" },
  { name: "Coppers and Brasses", slug: "coppers-and-brasses", homepage: "https://coppersandbrasses.com/", tier: "okay" },
  { name: "Darden Studio", slug: "darden-studio", homepage: "https://www.dardenstudio.com/", tier: "okay" },
  { name: "Colt Type", slug: "colt-type", homepage: "https://wearecolt.com/", tier: "okay" },
  { name: "Dharma Type", slug: "dharma-type", homepage: "https://dharmatype.com/", tier: "okay" },
  { name: "XYZ Type", slug: "xyz-type", homepage: "https://xyztype.com/", tier: "okay" },
  { name: "Kilotype", slug: "kilotype", homepage: "https://kilotype.de/", tier: "okay" },
  { name: "KOMETA Typefaces", slug: "kometa-typefaces", homepage: "https://www.kometa.xyz/", tier: "okay" },
  { name: "Kurppa Hosk Type", slug: "kurppa-hosk-type", homepage: "https://khtype.com/", tier: "okay" },
  { name: "Gradient", slug: "gradient", homepage: "https://wearegradient.net/", tier: "okay" },
  { name: "Letters from Sweden", slug: "letters-from-sweden", homepage: "https://lettersfromsweden.se/", tier: "okay" },
  // Batch 6
  { name: "East of Rome", slug: "east-of-rome", homepage: "https://eastofrome.com/", tier: "okay" },
  { name: "Commercial Classics", slug: "commercial-classics", homepage: "https://commercialclassics.com/", tier: "okay" },
  { name: "HvD Fonts", slug: "hvd-fonts", homepage: "https://www.hvdfonts.com/", tier: "okay" },
  { name: "Connary Fagen", slug: "connary-fagen", homepage: "https://connary.com/", tier: "okay" },
  { name: "Narrow Type", slug: "narrow-type", homepage: "https://www.narrowtype.com/", tier: "okay" },
  { name: "TypeTogether", slug: "type-together", homepage: "https://www.type-together.com/", tier: "okay" },
  { name: "Suitcase Type Foundry", slug: "suitcase-type", homepage: "https://www.suitcasetype.com/", tier: "okay" },
  { name: "Lettermatic", slug: "lettermatic", homepage: "https://lettermatic.com/", tier: "okay" },
  { name: "Radim Pesko", slug: "radim-pesko", homepage: "https://radimpesko.com/", tier: "okay" },
  { name: "The Foundry Types", slug: "the-foundry-types", homepage: "https://www.thefoundrytypes.com/", tier: "okay" },
  { name: "Type Forward", slug: "type-forward", homepage: "https://www.typeforward.com/", tier: "okay" },
  { name: "Nikolas Type", slug: "nikolas-type", homepage: "https://www.nikolastype.com/", tier: "okay" },
  { name: "Death of Typography", slug: "death-of-typography", homepage: "https://deathoftypography.com/", tier: "okay" },
  { name: "Monkey Type", slug: "monkey-type", homepage: "https://monkeytype.xyz/", tier: "okay" },
  { name: "TypeType", slug: "type-type", homepage: "https://typetype.org/", tier: "okay" },
  { name: "ECAL Typefaces", slug: "ecal-typefaces", homepage: "https://ecal-typefaces.ch/", tier: "okay" },
  { name: "WELTKERN", slug: "weltkern", homepage: "https://www.weltkern.com/", tier: "okay" },
  { name: "Village", slug: "village", homepage: "https://vllg.com/", tier: "okay" },
  { name: "Dirty Line Studio", slug: "dirty-line-studio", homepage: "https://dirtylinestudio.com/", tier: "okay" },
  { name: "Mojomox", slug: "mojomox", homepage: "https://fonts.mojomox.com/", tier: "okay" },
  { name: "205TF", slug: "205tf", homepage: "https://www.205.tf/", tier: "okay" },
  { name: "Fable", slug: "fable", homepage: "https://fable.design/", tier: "best" },
  { name: "Arkitype", slug: "arkitype", homepage: "https://www.arkitype.co/", tier: "best" },
  { name: "Crescenzi", slug: "crescenzi", homepage: "https://crescenzi.co/", tier: "best" },
  { name: "Lift Type", slug: "lift-type", homepage: "https://www.lift-type.fr/", tier: "best" },
  { name: "Ultra Kuhl", slug: "ultra-kuhl", homepage: "https://ultra-kuhl.com/", tier: "best" },
  { name: "Bold Monday", slug: "bold-monday", homepage: "https://www.boldmonday.com/", tier: "okay" },
  { name: "Letterjuice", slug: "letterjuice", homepage: "http://letterjuice.cat/", tier: "okay" },
  { name: "SilverStag Type", slug: "silverstag-type", homepage: "https://silverstagtype.com/", tier: "okay" },
  { name: "Milieu Grotesque", slug: "milieu-grotesque", homepage: "http://www.milieugrotesque.com/", tier: "okay" },
  // Batch 7
  { name: "Hot Type", slug: "hot-type", homepage: "https://hottype.co/", tier: "best" },
  { name: "Order", slug: "order", homepage: "https://order.design/", tier: "okay" },
  { name: "Luzi Type", slug: "luzi-type", homepage: "https://www.luzi-type.ch/", tier: "best" },
  { name: "Double Dagger", slug: "double-dagger", homepage: "https://www.doubledagger.xyz/", tier: "okay" },
  { name: "Indian Type Foundry", slug: "indian-type-foundry", homepage: "https://www.indiantypefoundry.com/", tier: "okay" },
  // Batch 8
  { name: "Tightype", slug: "tightype", homepage: "https://tightype.com/", tier: "okay" },
  { name: "Pizza Typefaces", slug: "pizza-typefaces", homepage: "https://typefaces.pizza/", tier: "okay" },
  { name: "That That Type", slug: "that-that-type", homepage: "https://thatthattype.com/", tier: "okay" },
  { name: "Fontfabric", slug: "fontfabric", homepage: "https://www.fontfabric.com/", tier: "okay" },
  { name: "TypeMates", slug: "typemates", homepage: "https://www.typemates.com/", tier: "okay" },
  // Batch 9
  { name: "DK Type", slug: "dktype", homepage: "https://dktype.com/", tier: "best" },
  { name: "Souvenir Typefaces", slug: "souvenir-typefaces", homepage: "https://souvenirtypefaces.xyz/", tier: "best" },
  { name: "The Northern Block", slug: "the-northern-block", homepage: "https://www.thenorthernblock.co.uk/", tier: "best" },
  { name: "Type of Feeling", slug: "type-of-feeling", homepage: "https://typeoffeeling.com/", tier: "best" },
  // Batch 11
  { name: "Store Norske Skriftkompani", slug: "store-norske-skriftkompani", homepage: "https://skriftkompani.no/", tier: "okay" },
  { name: "Latinotype", slug: "latinotype", homepage: "https://www.latinotype.com/", tier: "okay" },
  { name: "Fonts from Folch", slug: "fonts-from-folch", homepage: "https://www.fontsfromfolch.com/", tier: "okay" },
  { name: "Brandon Nickerson", slug: "brandon-nickerson", homepage: "https://www.bnicks.com/", tier: "okay" },
  { name: "Formerly Known", slug: "formerly-known", homepage: "https://formerly-known.com/", tier: "okay" },
  { name: "Supercontinente", slug: "supercontinente", homepage: "https://supercontinente.com/", tier: "okay" },
  { name: "R-Typography", slug: "r-typography", homepage: "https://www.r-typography.com/", tier: "okay" },
  { name: "Fontshare", slug: "fontshare", homepage: "https://www.fontshare.com/", tier: "okay" },
  { name: "Open Foundry", slug: "open-foundry", homepage: "https://open-foundry.com/", tier: "okay" },
  { name: "Free Faces", slug: "free-faces", homepage: "https://www.freefaces.gallery/", tier: "okay" },
  // Batch 10
  { name: "ALT.tf", slug: "alt-tf", homepage: "https://alt-tf.com/", tier: "okay" },
  { name: "Black Foundry", slug: "black-foundry", homepage: "https://black-foundry.com/", tier: "okay" },
  { name: "Collletttivo", slug: "collletttivo", homepage: "https://www.collletttivo.it/", tier: "okay" },
  { name: "Dot Colon", slug: "dot-colon", homepage: "https://dotcolon.net/", tier: "okay" },
  { name: "Gallery Type", slug: "gallery-type", homepage: "https://gallerytype.com/", tier: "okay" },
  { name: "Just Another Foundry", slug: "just-another-foundry", homepage: "https://justanotherfoundry.com/", tier: "okay" },
  { name: "Lettermin", slug: "lettermin", homepage: "https://lettermin.com/", tier: "okay" },
  { name: "lo-ol Type", slug: "lo-ol-type", homepage: "https://www.lo-ol.design/", tier: "okay" },
  { name: "Monokrom", slug: "monokrom", homepage: "https://monokrom.no/", tier: "okay" },
  { name: "Off Type", slug: "off-type", homepage: "https://off-type.com/", tier: "okay" },
  { name: "Patio Foundry", slug: "patio-foundry", homepage: "https://patiofoundry.com/", tier: "okay" },
  { name: "Process Type Foundry", slug: "process-type-foundry", homepage: "https://processtypefoundry.com/", tier: "okay" },
  { name: "Regular Bold Italic", slug: "regular-bold-italic", homepage: "https://regularbolditalic.com/", tier: "okay" },
  { name: "Rosetta", slug: "rosetta", homepage: "https://rosettatype.com/", tier: "okay" },
  { name: "Smuss Type Kiosk", slug: "smuss-type-kiosk", homepage: "https://typekiosk.smuss.studio/", tier: "okay" },
  { name: "Studio Feixen Fonts", slug: "studio-feixen-fonts", homepage: "https://fonts.studiofeixen.ch/", tier: "okay" },
  { name: "Studio Triple", slug: "studio-triple", homepage: "https://studiotriple.fr/", tier: "okay" },
  { name: "TYPE BY", slug: "type-by", homepage: "https://www.typeby.com/", tier: "okay" },
  { name: "Zetafonts", slug: "zetafonts", homepage: "https://www.zetafonts.com/", tier: "okay" },
];

// Foundries confirmed unscrapable — JS-rendered, bot-blocked, or no listing page.
// domain matches foundries.json domain field.
export const BLOCKED_FOUNDRIES: { domain: string; name: string; reason: string }[] = [
  { domain: "aeonik.co.uk", name: "Aeonik", reason: "redirects to CoType; CoType is JS-rendered" },
  { domain: "cotypefoundry.com", name: "CoType Foundry", reason: "JS-rendered, no crawlable listing" },
  { domain: "supply.family", name: "Zarma Type", reason: "reseller aggregator, not a single foundry page" },
  { domain: "studioplums.com", name: "Ian Adjeidu", reason: "portfolio site, no listing page" },
  { domain: "experim-etal.lettersetal.co.uk", name: "Lettersetal", reason: "JS-rendered" },
  { domain: "limitype.com", name: "Limitype", reason: "JS-rendered, no crawlable listing" },
  { domain: "mcletters.co", name: "McLetters", reason: "JS-rendered" },
  { domain: "capitalics.wtf", name: "Capitalics", reason: "JS-rendered" },
  { domain: "typokompanii.com", name: "Tüpokompanii", reason: "JS-rendered" },
  { domain: "threedotstype.com", name: "Threedotstype", reason: "JS-rendered, no listing page" },
  { domain: "typeverything.com", name: "Typeverything", reason: "inspiration blog, not a foundry" },
  { domain: "behance.net", name: "Rajesh Rajput", reason: "Behance portfolio, not indexable" },
  { domain: "castletype.com", name: "Castle Type", reason: "old static site, no structured listing" },
  { domain: "youworkforthem.com", name: "YouWorkForThem", reason: "reseller marketplace, not a foundry" },
  { domain: "paratype.com", name: "Paratype", reason: "large catalogue, no structured listing page" },
  { domain: "colophon-foundry.org", name: "Colophon", reason: "JS-rendered, no crawlable listing" },
  { domain: "familytype.co", name: "Family Type", reason: "JS-rendered, no crawlable listing" },
  { domain: "outofthedark.xyz", name: "Out of the Dark", reason: "JS-rendered, no crawlable listing" },
  { domain: "ott-foundry.com", name: "OTT Foundry", reason: "JS-rendered, no crawlable listing" },
  { domain: "vllg.com", name: "Village", reason: "React SPA, no crawlable listing" },
  { domain: "205.tf", name: "205TF", reason: "Next.js SPA, no crawlable listing" },
  { domain: "monkeytype.xyz", name: "Monkey Type", reason: "SPA, no crawlable listing" },
  { domain: "ultra-kuhl.com", name: "Ultra Kuhl", reason: "rebranded as Rellence, site unreachable" },
  { domain: "commercialclassics.com", name: "Commercial Classics", reason: "SSL certificate expired" },
  { domain: "milieugrotesque.com", name: "Milieu Grotesque", reason: "redirects to MyFonts, no own listing" },
];

export function getFoundryBySlug(slug: string): FoundryInfo | undefined {
  return FOUNDRIES.find((f) => f.slug === slug);
}

export function getFoundryByName(name: string): FoundryInfo | undefined {
  return FOUNDRIES.find((f) => f.name === name);
}
