// Foundry names in the typeface files don't match the bookmark titles in
// data/foundries.json ("Klim Type Foundry" vs "Klim Type Foundry - Home"),
// so homepage URLs and tiers are pinned here for the 13 indexed foundries.

export type FoundryInfo = {
  name: string; // as it appears in the typeface files
  slug: string;
  homepage: string;
  tier: "best" | "good" | "okay" | "notgood";
};

export const FOUNDRIES: FoundryInfo[] = [
  // Batch 6
  // Batch 7
  // Batch 8
  // Batch 9
  // Batch 11
  // Batch 10
  // Batch 12
  // Batch 13
  // Batch 14
  // Batch 15
  // Batch 16
  // Batch 17
  // Batch 18
  // Batch 21
  // Batch 22
  // Batch 23 — typefoundry.directory gap-fill
  // Batch 24 — remaining typefoundry.directory accessible foundries
  // Batch 23 — featuredtype.com gap-fill
  // Batch 25–26 — manually indexed foundries
  // Batch 30 — Supply.Family creators
  // Batch 29 — okay-tier gap-fill
  // Batch 24 — gap-fill registrations (data indexed but foundry-map entry missing)
  { name: "205TF", slug: "205tf", homepage: "https://www.205.tf/", tier: "okay" },
  { name: "205TF", slug: "205tf", homepage: "https://www.205.tf/", tier: "okay" },
  { name: "29LT", slug: "29lt", homepage: "https://www.29lt.com/", tier: "best" },
  { name: "403TF", slug: "403tf", homepage: "https://supply.family/", tier: "okay" },
  { name: "6TM Magazine", slug: "6tm-magazine", homepage: "https://shop.6tm-magazine.com/", tier: "okay" },
  { name: "A is for", slug: "a-is-for", homepage: "https://aisforfonts.com/", tier: "okay" },
  { name: "A Practice for Everyday Life", slug: "a-practice-for-everyday-life", homepage: "https://apracticeforeverydaylife.com/", tier: "okay" },
  { name: "A Type of Amigo", slug: "a-type-of-amigo", homepage: "https://atypeofamigo.com/", tier: "best" },
  { name: "a.Foundry", slug: "a-foundry", homepage: "https://a-foundry.com/", tier: "best" },
  { name: "A+", slug: "a", homepage: "https://www.futurefonts.com/aplus/", tier: "okay" },
  { name: "A2-Type", slug: "a2-type", homepage: "https://a2-type.co.uk/", tier: "best" },
  { name: "ABC Etc Inc", slug: "abc-etc", homepage: "http://www.abc-etc.com/", tier: "okay" },
  { name: "Abhijit Menon", slug: "abhijit-menon", homepage: "https://www.futurefonts.com/abhijit/", tier: "okay" },
  { name: "About Type", slug: "about-type", homepage: "https://abouttype.com/", tier: "okay" },
  { name: "Abstract Office", slug: "abstract-office", homepage: "https://abstractoffice.xyz/", tier: "best" },
  { name: "Abyme", slug: "abyme", homepage: "https://www.abyme.net", tier: "okay" },
  { name: "ÁccentiaType", slug: "accentiatype", homepage: "https://accentiatype.com/", tier: "okay" },
  { name: "AcidType", slug: "acidtype", homepage: "https://supply.family/", tier: "okay" },
  { name: "Adam Ladd Design", slug: "adam-ladd-design", homepage: "https://ladd-design.com/", tier: "best" },
  { name: "Aeiou Tools", slug: "aeiou-tools", homepage: "https://aeiou.tools/", tier: "okay" },
  { name: "Aesthetic Type", slug: "aesthetic-type", homepage: "https://aesthetictype.com", tier: "okay" },
  { name: "AinsiFont", slug: "ainsifont", homepage: "https://www.ainsifont.com/", tier: "okay" },
  { name: "Aiyari Studio", slug: "aiyari-studio", homepage: "https://aiyaristudio.com/", tier: "okay" },
  { name: "Alexandre Créquer", slug: "alexandre-crequer", homepage: "https://www.alex-creq.com/", tier: "okay" },
  { name: "AlfaType Fonts Foundry", slug: "alfatype-fonts-foundry", homepage: "https://www.alfatypefonts.com/", tier: "okay" },
  { name: "Alias", slug: "alias", homepage: "https://alias.fonts.xyz/", tier: "okay" },
  { name: "AllCaps", slug: "allcaps", homepage: "https://www.allcapstype.com/", tier: "best" },
  { name: "Almarena", slug: "almarena", homepage: "https://almarenafoundry.com/", tier: "best" },
  { name: "ALT.tf", slug: "alt-tf", homepage: "https://alt-tf.com/", tier: "okay" },
  { name: "Amorfa Type", slug: "amorfa-type", homepage: "https://supply.family/", tier: "okay" },
  { name: "Anton Koovit", slug: "anton-koovit", homepage: "https://antonkoovit.com/", tier: "best" },
  { name: "Antonin Bertrand", slug: "antonin-bertrand", homepage: "https://antoninbertrand.com/", tier: "okay" },
  { name: "Any-Type® Foundry", slug: "any-type-foundry", homepage: "https://supply.family/", tier: "okay" },
  { name: "Apex Foundry", slug: "apex-foundry", homepage: "https://www.apextypefoundry.com/", tier: "okay" },
  { name: "Approximate Type", slug: "approximate-type", homepage: "https://approxtype.com/", tier: "okay" },
  { name: "Arcane Type Foundry", slug: "arcane-type-foundry", homepage: "https://www.arcanetype.com", tier: "okay" },
  { name: "Archive Foundry", slug: "archive-foundry", homepage: "https://www.archivefoundry.co/", tier: "best" },
  { name: "Arillatype", slug: "arillatype", homepage: "https://arillatype.studio/", tier: "best" },
  { name: "Arkitype", slug: "arkitype", homepage: "https://www.arkitype.co/", tier: "best" },
  { name: "ArrowType", slug: "arrowtype", homepage: "https://www.arrowtype.com/", tier: "okay" },
  { name: "Atelier René Knip", slug: "atelier-rene-knip", homepage: "https://atelierreneknip.com/", tier: "okay" },
  { name: "atipo foundry", slug: "atipo-foundry", homepage: "https://www.atipofoundry.com/", tier: "best" },
  { name: "Atipo Foundry", slug: "atipo-foundry", homepage: "https://www.atipofoundry.com/", tier: "okay" },
  { name: "Atlas Fonts", slug: "atlas-fonts", homepage: "https://www.atlasfonts.com", tier: "okay" },
  { name: "Atypical", slug: "atypical", homepage: "https://atypical.gr/", tier: "okay" },
  { name: "AUTHENTIC", slug: "authentic", homepage: "https://authentic.website/", tier: "okay" },
  { name: "Autograph", slug: "autograph", homepage: "https://supply.family/", tier: "okay" },
  { name: "Avondale Type Co.", slug: "avondale-type", homepage: "https://avondaletypeco.com", tier: "okay" },
  { name: "b•v-h type", slug: "bvh-type", homepage: "https://bvhtype.com/", tier: "okay" },
  { name: "Badson Type", slug: "badson-type", homepage: "https://badsontype.com", tier: "okay" },
  { name: "Bagerich Type Foundry", slug: "bagerich-type-foundry", homepage: "https://supply.family/", tier: "okay" },
  { name: "Bal Foundry", slug: "bal-foundry", homepage: "https://www.bal-foundry.com", tier: "okay" },
  { name: "Balto / Type Supply", slug: "balto-type-supply", homepage: "https://typesupply.com/", tier: "okay" },
  { name: "Barnbrook", slug: "barnbrook", homepage: "https://barnbrook.net", tier: "okay" },
  { name: "Bastarda", slug: "bastarda", homepage: "https://bastardatype.com/", tier: "best" },
  { name: "bb-bureau", slug: "bb-bureau", homepage: "https://bb-bureau.fr/", tier: "okay" },
  { name: "Beasts of England", slug: "beasts-of-england", homepage: "https://beastsofengland.co", tier: "okay" },
  { name: "Bentype Studio", slug: "bentype-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "Big Fog Foundry", slug: "big-fog-foundry", homepage: "https://foundry.bigfog.co/", tier: "okay" },
  { name: "Bijou Type", slug: "bijou-type", homepage: "https://bijoutype.com", tier: "okay" },
  { name: "Binnenland", slug: "binnenland", homepage: "https://www.binnenland.ch/", tier: "best" },
  { name: "Bitstream", slug: "bitstream", homepage: "https://www.monotype.com/", tier: "okay" },
  { name: "Black Foundry", slug: "black-foundry", homepage: "https://black-foundry.com/", tier: "okay" },
  { name: "Blackletra", slug: "blackletra", homepage: "https://blackletra.com", tier: "okay" },
  { name: "Blanco Letters", slug: "blanco-letters", homepage: "https://www.blancoletters.com/", tier: "okay" },
  { name: "Blankids", slug: "blankids", homepage: "https://supply.family/", tier: "okay" },
  { name: "Blast Foundry", slug: "blast-foundry", homepage: "https://blast-foundry.com/", tier: "okay" },
  { name: "Blaze Type", slug: "blaze-type", homepage: "https://blazetype.eu/", tier: "best" },
  { name: "Bloom Type", slug: "bloom-type", homepage: "https://bloomtype.com", tier: "okay" },
  { name: "Bold Decisions", slug: "bold-decisions", homepage: "https://bold-decisions.biz", tier: "okay" },
  { name: "Bold Monday", slug: "bold-monday", homepage: "https://www.boldmonday.com/", tier: "okay" },
  { name: "Bold Studio", slug: "bold-studio", homepage: "http://bold.studio", tier: "okay" },
  { name: "Bolid System", slug: "bolid-system", homepage: "https://bolidsystem.ch", tier: "okay" },
  { name: "Boulevard LAB", slug: "boulevard-lab", homepage: "https://boulevardlab.com/", tier: "okay" },
  { name: "Branding with Type", slug: "branding-with-type", homepage: "https://brandingwithtype.com", tier: "okay" },
  { name: "Brandon Nickerson", slug: "brandon-nickerson", homepage: "https://www.bnicks.com/", tier: "okay" },
  { name: "Bretagne", slug: "bretagne", homepage: "http://www.bretagnebretagne.fr", tier: "okay" },
  { name: "Briefcase Type Foundry", slug: "briefcase-type-foundry", homepage: "https://www.briefcasetype.com", tier: "okay" },
  { name: "British Standard Type", slug: "british-standard-type", homepage: "https://www.britishstandardtype.xyz/", tier: "best" },
  { name: "Brownfox", slug: "brownfox", homepage: "https://brownfox.org", tier: "okay" },
  { name: "Brutal Types", slug: "brutal-types", homepage: "https://www.brutaltypes.com", tier: "okay" },
  { name: "BTYPE", slug: "btype", homepage: "https://supply.family/", tier: "okay" },
  { name: "Bureau Brut", slug: "bureau-brut", homepage: "https://bureaubrut.com/", tier: "best" },
  { name: "BurnType", slug: "burntype", homepage: "https://burntype.com/", tier: "best" },
  { name: "Burrow Lab", slug: "burrow-lab", homepage: "https://burrow-lab.fonts.xyz/", tier: "okay" },
  { name: "Cake Type", slug: "cake-type", homepage: "https://www.caketype.com", tier: "okay" },
  { name: "Calame.Bureau", slug: "calame-bureau", homepage: "https://arthurcalame.com/", tier: "okay" },
  { name: "Calderón", slug: "calderon", homepage: "https://www.estudiocalderon.com/", tier: "best" },
  { name: "Camelot", slug: "camelot", homepage: "https://camelot-typefaces.com/", tier: "best" },
  { name: "Canada Type", slug: "canada-type", homepage: "https://canadatype.com/", tier: "best" },
  { name: "Cantrell Type", slug: "cantrell-type", homepage: "https://cantrelltype.com", tier: "okay" },
  { name: "Cape Arcona", slug: "cape-arcona", homepage: "https://www.cape-arcona.com", tier: "okay" },
  { name: "Capitalics", slug: "capitalics", homepage: "https://capitalics.wtf/", tier: "best" },
  { name: "Carmel Type Co.", slug: "carmel-type", homepage: "https://carmeltype.co", tier: "okay" },
  { name: "Casloop Studio", slug: "casloop-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "CAST", slug: "cast", homepage: "https://www.c-a-s-t.com/", tier: "best" },
  { name: "Central Type", slug: "central-type", homepage: "https://centraltype.com/", tier: "okay" },
  { name: "Character Type", slug: "character-type", homepage: "https://charactertype.com", tier: "okay" },
  { name: "Charlotte Rohde", slug: "charlotte-rohde", homepage: "https://www.charlotterohde.de", tier: "okay" },
  { name: "Chill Type", slug: "chill-type", homepage: "https://chilltype.com/", tier: "okay" },
  { name: "CJ Type", slug: "cj-type", homepage: "http://www.cjtype.com", tier: "okay" },
  { name: "Claude Type", slug: "claude-type", homepage: "https://claudetype.com/", tier: "best" },
  { name: "Collletttivo", slug: "collletttivo", homepage: "https://www.collletttivo.it/", tier: "okay" },
  { name: "Colt Type", slug: "colt-type", homepage: "https://wearecolt.com/", tier: "okay" },
  { name: "Comma Type", slug: "comma-type", homepage: "https://www.commatype.com", tier: "okay" },
  { name: "Commercial Classics", slug: "commercial-classics", homepage: "https://commercialclassics.com/", tier: "okay" },
  { name: "Commercial Type", slug: "commercial-type", homepage: "https://commercialtype.com/", tier: "okay" },
  { name: "Connary Fagen", slug: "connary-fagen", homepage: "https://connary.com/", tier: "okay" },
  { name: "Contrast Foundry", slug: "contrast-foundry", homepage: "https://contrastfoundry.com", tier: "okay" },
  { name: "Coppers and Brasses", slug: "coppers-and-brasses", homepage: "https://coppersandbrasses.com/", tier: "okay" },
  { name: "Corentin Noyer", slug: "corentin-noyer", homepage: "https://www.corentinoyer.fr", tier: "okay" },
  { name: "CoType Foundry", slug: "cotype-foundry", homepage: "https://cotypefoundry.com/", tier: "best" },
  { name: "Counter Forms", slug: "counter-forms", homepage: "https://counter-forms.com/", tier: "okay" },
  { name: "Crescenzi", slug: "crescenzi", homepage: "https://crescenzi.co/", tier: "best" },
  { name: "Crown Type", slug: "crown-type", homepage: "https://crowntype.com", tier: "okay" },
  { name: "Dalton Maag", slug: "dalton-maag", homepage: "https://www.daltonmaag.com/", tier: "best" },
  { name: "Darden Studio", slug: "darden-studio", homepage: "https://www.dardenstudio.com/", tier: "okay" },
  { name: "Daria Cohen", slug: "daria-cohen", homepage: "https://contemporarytype.com/", tier: "best" },
  { name: "David Einwaller", slug: "david-einwaller", homepage: "https://shop.deinwaller.com", tier: "okay" },
  { name: "David Jonathan Ross", slug: "david-jonathan-ross", homepage: "https://djr.com/", tier: "okay" },
  { name: "Daytona Mess", slug: "daytona-mess", homepage: "https://daytona-mess.fonts.xyz/", tier: "notgood" },
  { name: "DDOTT", slug: "ddott", homepage: "https://ddott.net/", tier: "okay" },
  { name: "Death of Typography", slug: "death-of-typography", homepage: "https://deathoftypography.com/", tier: "okay" },
  { name: "Delta Bravo Type", slug: "delta-bravo-type", homepage: "https://www.deltabravotype.com", tier: "okay" },
  { name: "Delve Fonts", slug: "delve-fonts", homepage: "https://delvefonts.com/", tier: "okay" },
  { name: "Denis Serebryakov", slug: "serebryakov", homepage: "https://type.today/en/journal/serebryakov", tier: "best" },
  { name: "Dennis Grauel", slug: "dennis-grauel", homepage: "https://dennisgrauel.com", tier: "okay" },
  { name: "Department of Letters", slug: "department-of-letters", homepage: "https://www.deptofletters.ca", tier: "okay" },
  { name: "Dharma Type", slug: "dharma-type", homepage: "https://dharmatype.com/", tier: "okay" },
  { name: "Dinamo Typefaces", slug: "dinamo-typefaces", homepage: "https://abcdinamo.com/", tier: "best" },
  { name: "Diorama Type Partners", slug: "diorama-type-partners", homepage: "https://www.dioramatypepartners.com", tier: "okay" },
  { name: "Dirty Line Studio", slug: "dirty-line-studio", homepage: "https://dirtylinestudio.com/", tier: "okay" },
  { name: "Dirty Line Studio", slug: "dirty-line-studio", homepage: "https://dirtylinestudio.com/", tier: "okay" },
  { name: "Displaay Type Foundry", slug: "displaay-type-foundry", homepage: "https://displaay.net/", tier: "best" },
  { name: "dito-typo", slug: "dito-typo", homepage: "https://dito-typo.com/", tier: "okay" },
  { name: "DK Type", slug: "dktype", homepage: "https://dktype.com/", tier: "best" },
  { name: "Domicile Foundry", slug: "domicile-foundry", homepage: "https://domicilefoundry.com", tier: "okay" },
  { name: "Dot Colon", slug: "dot-colon", homepage: "https://dotcolon.net/", tier: "okay" },
  { name: "Double Dagger", slug: "double-dagger", homepage: "https://www.doubledagger.xyz/", tier: "okay" },
  { name: "Dreamtype", slug: "dreamtype", homepage: "https://dreamtype.xyz", tier: "okay" },
  { name: "Due Studio", slug: "due-studio", homepage: "https://www.due-studio.com/", tier: "best" },
  { name: "Dunwich Type", slug: "dunwich-type", homepage: "https://dunwichtype.com", tier: "okay" },
  { name: "Duong Tran", slug: "duong-tran", homepage: "https://duong-tran.fonts.xyz/", tier: "okay" },
  { name: "E162", slug: "e162", homepage: "http://e162.eu", tier: "okay" },
  { name: "East of Rome", slug: "east-of-rome", homepage: "https://eastofrome.com/", tier: "okay" },
  { name: "ECAL Typefaces", slug: "ecal-typefaces", homepage: "https://ecal-typefaces.ch/", tier: "okay" },
  { name: "Edignwn Type", slug: "edignwn-type", homepage: "https://supply.family/", tier: "okay" },
  { name: "Edition Studio", slug: "edition-studio", homepage: "https://edition.studio", tier: "okay" },
  { name: "EK Type", slug: "ek-type", homepage: "https://ektype.in", tier: "best" },
  { name: "Element Type", slug: "element-type", homepage: "https://elementtype.com/", tier: "best" },
  { name: "Elena Schneider", slug: "elena-schneider", homepage: "https://elenaschneider.com/", tier: "okay" },
  { name: "Emtype Foundry", slug: "emtype-foundry", homepage: "https://emtype.net", tier: "best" },
  { name: "EPI", slug: "epitype", homepage: "https://epitype.xyz", tier: "okay" },
  { name: "Erkin Karamemet", slug: "erkin-karamemet", homepage: "https://erkinkaramemet.com/", tier: "okay" },
  { name: "ETC Typefaces", slug: "etc-typefaces", homepage: "https://etceteratype.co", tier: "okay" },
  { name: "Extra Type", slug: "extra-type", homepage: "https://extratype.com", tier: "okay" },
  { name: "Extraset", slug: "extraset", homepage: "https://extraset.ch/", tier: "best" },
  { name: "F37 Foundry", slug: "f37-foundry", homepage: "https://www.f37foundry.com/", tier: "okay" },
  { name: "Fable", slug: "fable", homepage: "https://fable.design/", tier: "best" },
  { name: "Facetype", slug: "facetype", homepage: "http://www.facetype.org", tier: "okay" },
  { name: "Faire Type", slug: "faire-type", homepage: "https://www.fairetype.com/", tier: "best" },
  { name: "Familiar Faces", slug: "familiar-faces", homepage: "https://familiarfaces.xyz", tier: "okay" },
  { name: "Family Type", slug: "family-type", homepage: "https://familytype.co/", tier: "best" },
  { name: "Famira Fonts", slug: "famira-fonts", homepage: "https://store.typenetwork.com/", tier: "okay" },
  { name: "Fantasia Type", slug: "fantasia-type", homepage: "https://www.fantasia-type.com", tier: "okay" },
  { name: "Fateh.Lab", slug: "fateh-lab", homepage: "https://supply.family/", tier: "okay" },
  { name: "Fatype", slug: "fatype", homepage: "https://fatype.com/", tier: "best" },
  { name: "FDI Type Foundry", slug: "fdi-type-foundry", homepage: "https://fdi-type.de", tier: "okay" },
  { name: "Febspace Studio", slug: "febspace-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "Feedtype", slug: "feedtype", homepage: "https://feedtype.ca", tier: "okay" },
  { name: "Feliciano Type", slug: "feliciano-type", homepage: "https://felicianotype.com/", tier: "okay" },
  { name: "Fer Cozzi", slug: "fer-cozzi", homepage: "https://fercozzi.com/", tier: "okay" },
  { name: "Finaltype", slug: "finaltype", homepage: "https://finaltype.de", tier: "okay" },
  { name: "Flatface Type", slug: "flatface-type", homepage: "https://supply.family/", tier: "okay" },
  { name: "Flavia Zimbardi", slug: "flavia-zimbardi", homepage: "https://flaviazim.com/", tier: "okay" },
  { name: "Flood Fonts", slug: "flood-fonts", homepage: "https://floodfonts.com/", tier: "okay" },
  { name: "Florian Karsten", slug: "catalogue", homepage: "https://fonts.floriankarsten.com/", tier: "best" },
  { name: "Florian Runge", slug: "florian-runge", homepage: "https://florianrunge.com/", tier: "okay" },
  { name: "FOLCH", slug: "folch", homepage: "https://fontsfromfolch.com/", tier: "okay" },
  { name: "Fonderie Bretagne", slug: "fonderie-bretagne", homepage: "https://fonderiebretagne.fr/", tier: "okay" },
  { name: "Font Bureau", slug: "font-bureau", homepage: "https://fontbureau.com/", tier: "best" },
  { name: "Font Club Belgica", slug: "font-club-belgica", homepage: "https://fontclubbelgica.com", tier: "okay" },
  { name: "Fontfabric", slug: "fontfabric", homepage: "https://www.fontfabric.com/", tier: "okay" },
  { name: "FontFont", slug: "fontfont", homepage: "https://www.fontfont.com/", tier: "okay" },
  { name: "Fonts from Folch", slug: "fonts-from-folch", homepage: "https://www.fontsfromfolch.com/", tier: "okay" },
  { name: "Fontshare", slug: "fontshare", homepage: "https://www.fontshare.com/", tier: "okay" },
  { name: "Fontwerk", slug: "fontwerk", homepage: "https://fontwerk.com/", tier: "best" },
  { name: "Forgery Type", slug: "forgery-type", homepage: "https://forgery.ventures", tier: "okay" },
  { name: "Forgotten Shapes", slug: "forgotten-shapes", homepage: "https://forgotten-shapes.com/", tier: "okay" },
  { name: "Formagari", slug: "formagari", homepage: "https://formagari.com/", tier: "okay" },
  { name: "Formerly Known", slug: "formerly-known", homepage: "https://formerly-known.com/", tier: "okay" },
  { name: "Formula Type", slug: "formula-type", homepage: "https://www.formulatype.com", tier: "okay" },
  { name: "Fort Foundry", slug: "fort-foundry", homepage: "https://fortfoundry.com", tier: "okay" },
  { name: "Foster Type", slug: "foster-type", homepage: "https://www.fostertype.com", tier: "okay" },
  { name: "Foundry Five", slug: "foundry-five", homepage: "https://foundryfivetype.com", tier: "okay" },
  { name: "FredsFonts", slug: "fredsfonts", homepage: "https://fredsfonts.fonts.xyz/", tier: "okay" },
  { name: "Free Faces", slug: "free-faces", homepage: "https://www.freefaces.gallery/", tier: "okay" },
  { name: "Freight Collection", slug: "freight-collection", homepage: "https://freightcollection.com/", tier: "best" },
  { name: "Frere-Jones", slug: "frere-jones", homepage: "https://frerejones.com", tier: "best" },
  { name: "Frost", slug: "frost", homepage: "https://frostype.xyz/", tier: "best" },
  { name: "Fuerte Type", slug: "fuerte-type", homepage: "https://www.fuertetype.com/", tier: "okay" },
  { name: "Furniture", slug: "furniture", homepage: "https://www.furniture.xyz", tier: "okay" },
  { name: "G-Type", slug: "g-type", homepage: "https://g-type.com", tier: "best" },
  { name: "Gallery Type", slug: "gallery-type", homepage: "https://gallerytype.com/", tier: "okay" },
  { name: "Garisman Studio", slug: "garisman-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "General Type Studio", slug: "general-type-studio", homepage: "https://www.generaltypestudio.com/", tier: "best" },
  { name: "Giulia Boggio", slug: "giulia-boggio", homepage: "https://giulia-boggio.fonts.xyz/", tier: "okay" },
  { name: "Glyphminds Studios", slug: "glyphminds-studios", homepage: "https://supply.family/", tier: "okay" },
  { name: "Glyphonic", slug: "glyphonic", homepage: "https://supply.family/", tier: "okay" },
  { name: "God Control", slug: "god-control", homepage: "https://supply.family/", tier: "okay" },
  { name: "Good Type Foundry", slug: "good-type-foundry", homepage: "https://goodtypefoundry.com/", tier: "okay" },
  { name: "Google Fonts", slug: "google-fonts", homepage: "https://fonts.google.com/", tier: "okay" },
  { name: "Gradient", slug: "gradient", homepage: "https://wearegradient.net/", tier: "okay" },
  { name: "Gridlounge Studio", slug: "gridlounge-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "Grilli Type", slug: "grilli-type", homepage: "https://www.grillitype.com/", tier: "best" },
  { name: "Groteskly Yours", slug: "groteskly-yours", homepage: "https://groteskly.xyz/", tier: "best" },
  { name: "Gruppo Due", slug: "gruppo-due", homepage: "https://gruppo-due.com", tier: "okay" },
  { name: "Güneş Muhittin", slug: "gunes-muhittin", homepage: "https://www.gunesmuhittin.com/", tier: "okay" },
  { name: "Hadrien Herzog", slug: "hadrien-herzog", homepage: "https://hadrien-herzog.fonts.xyz/", tier: "okay" },
  { name: "HAL Typefaces", slug: "hal-typefaces", homepage: "https://type.hanli.eu/", tier: "okay" },
  { name: "Hard Type", slug: "hard-type", homepage: "https://hardtype.xyz", tier: "okay" },
  { name: "Heavyweight", slug: "heavyweight", homepage: "https://heavyweight-type.com/", tier: "okay" },
  { name: "Herzberg Design", slug: "herzberg-design", homepage: "https://www.herzbergdesign.com", tier: "okay" },
  { name: "HEX", slug: "hex", homepage: "https://hex.xyz/", tier: "okay" },
  { name: "Hipertipo", slug: "hipertipo", homepage: "https://www.hipertipo.com", tier: "okay" },
  { name: "Hoefler & Co", slug: "hoefler-co", homepage: "https://www.typography.com/", tier: "notgood" },
  { name: "Holdon Type", slug: "holdon-type", homepage: "https://www.holdontype.design/", tier: "okay" },
  { name: "HolisFonts", slug: "holisfonts", homepage: "https://supply.family/", tier: "okay" },
  { name: "Hora Nocte", slug: "hora-nocte", homepage: "https://supply.family/", tier: "okay" },
  { name: "Hot Type", slug: "hot-type", homepage: "https://hottype.co/", tier: "best" },
  { name: "House Industries", slug: "house-industries", homepage: "https://housefonts.com/", tier: "best" },
  { name: "Hungarumlaut", slug: "hungarumlaut", homepage: "https://hungarumlaut.com", tier: "okay" },
  { name: "Hurme Design", slug: "hurme-design", homepage: "https://hurmedesign.com/", tier: "okay" },
  { name: "HvD Fonts", slug: "hvd-fonts", homepage: "https://www.hvdfonts.com/", tier: "okay" },
  { name: "Hypertype", slug: "hypertype", homepage: "http://hypertype.xyz", tier: "okay" },
  { name: "Ian Adjeidu", slug: "ian-adjeidu", homepage: "https://studioplums.com/", tier: "notgood" },
  { name: "Identity Letters", slug: "identity-letters", homepage: "https://www.identity-letters.com", tier: "okay" },
  { name: "In-House Intl", slug: "in-house-intl", homepage: "https://weareinhouse.com", tier: "okay" },
  { name: "Inari Type", slug: "inari-type", homepage: "https://inaritype.com", tier: "okay" },
  { name: "Increments", slug: "increments", homepage: "https://www.increments.cc/", tier: "okay" },
  { name: "Indian Type Foundry", slug: "indian-type-foundry", homepage: "https://www.indiantypefoundry.com/", tier: "okay" },
  { name: "Inhouse Type", slug: "inhouse-type", homepage: "https://inhousetype.com/", tier: "okay" },
  { name: "Interval Type", slug: "interval-type", homepage: "https://intervaltype.com/", tier: "best" },
  { name: "Itemzero", slug: "itemzero", homepage: "https://shop.itemzero.com", tier: "okay" },
  { name: "Ivy Foundry", slug: "ivy-foundry", homepage: "https://ivyfoundry.com", tier: "okay" },
  { name: "J Foundry", slug: "j-foundry", homepage: "https://jfoundry.com", tier: "okay" },
  { name: "Jamie Clark Type", slug: "jamie-clark-type", homepage: "https://www.jamieclarketype.com", tier: "okay" },
  { name: "Jeremy Tankard Typography", slug: "jeremy-tankard", homepage: "https://typography.net", tier: "best" },
  { name: "Jessica Hische", slug: "jessica-hische", homepage: "https://jessicahische.shop/", tier: "okay" },
  { name: "Jonas Pelzer", slug: "jonas-pelzer", homepage: "http://typefaces.jonaspelzer.com", tier: "okay" },
  { name: "JP Flexner", slug: "jp-flexner", homepage: "https://www.jpflexner.com/", tier: "okay" },
  { name: "JS Type", slug: "js-type", homepage: "https://js-type.fonts.xyz/", tier: "okay" },
  { name: "JTD Type", slug: "jtd-type", homepage: "https://jtdtype.com", tier: "okay" },
  { name: "July Type", slug: "july-type", homepage: "https://www.julytype.com", tier: "okay" },
  { name: "Jung-Lee Type Foundry", slug: "jung-lee-type", homepage: "https://j-ltf.com", tier: "okay" },
  { name: "Juri Zæch", slug: "juri-zaech", homepage: "https://www.juri-zaech.com/", tier: "okay" },
  { name: "Just Another Foundry", slug: "just-another-foundry", homepage: "https://justanotherfoundry.com/", tier: "okay" },
  { name: "K73 TF", slug: "k73-tf", homepage: "https://supply.family/", tier: "okay" },
  { name: "Kanon Foundry", slug: "kanon-foundry", homepage: "https://kanonfoundry.com", tier: "okay" },
  { name: "Karsten Lücke", slug: "karsten-lucke", homepage: "https://kltf.de/", tier: "best" },
  { name: "Kerns & Cairns", slug: "kerns-and-cairns", homepage: "https://www.kernsandcairns.com", tier: "okay" },
  { name: "Keussel Studio", slug: "keussel-studio", homepage: "https://keussel-studio.fonts.xyz/", tier: "okay" },
  { name: "Kilotype", slug: "kilotype", homepage: "https://kilotype.de/", tier: "okay" },
  { name: "Kimera", slug: "kimera", homepage: "https://kimeracorp.eu", tier: "okay" },
  { name: "Kind Type Foundry", slug: "kind-type-foundry", homepage: "https://kindtype.co/", tier: "okay" },
  { name: "Kiosk Fonts", slug: "kiosk-fonts", homepage: "https://kiosk-fonts.de", tier: "okay" },
  { name: "Kirjatehnika", slug: "kirjatehnika", homepage: "https://www.kirjatehnika.ee", tier: "okay" },
  { name: "Klim Type Foundry", slug: "klim-type-foundry", homepage: "https://klim.co.nz/", tier: "best" },
  { name: "KOMETA Typefaces", slug: "kometa-typefaces", homepage: "https://www.kometa.xyz/", tier: "okay" },
  { name: "Kontour", slug: "kontour", homepage: "https://kontour.com/", tier: "okay" },
  { name: "Kostic Type", slug: "kostic-type", homepage: "https://kostictype.com", tier: "okay" },
  { name: "Kurppa Hosk Type", slug: "kurppa-hosk-type", homepage: "https://khtype.com/", tier: "okay" },
  { name: "Kyiv Type Foundry", slug: "kyiv-type-foundry", homepage: "https://kyivtypefoundry.com", tier: "okay" },
  { name: "La Bolde Vita", slug: "la-bolde-vita", homepage: "https://www.laboldevita.com", tier: "okay" },
  { name: "La Police", slug: "la-police", homepage: "https://lapolice.ch", tier: "okay" },
  { name: "Labor and Wait", slug: "labor-and-wait", homepage: "https://www.laborandwait.xyz/", tier: "okay" },
  { name: "Laïc", slug: "laic", homepage: "https://laic.pl", tier: "okay" },
  { name: "Latinotype", slug: "latinotype", homepage: "https://www.latinotype.com/", tier: "okay" },
  { name: "Latinotype", slug: "latinotype", homepage: "https://latinotype.com/", tier: "okay" },
  { name: "Laura Worthington Design", slug: "laura-worthington", homepage: "https://lauraworthingtondesign.com", tier: "okay" },
  { name: "Lazydogs Typefoundry", slug: "lazydogs-typefoundry", homepage: "https://lazydogs.de/", tier: "okay" },
  { name: "Leinster Type", slug: "leinster-type", homepage: "https://www.leinstertype.com/", tier: "best" },
  { name: "Lena Weber", slug: "lena-weber", homepage: "https://www.monomodular.de/", tier: "notgood" },
  { name: "Léon Hugues", slug: "leon-hugues", homepage: "https://leon-hugues.fonts.xyz/", tier: "okay" },
  { name: "Letterjuice", slug: "letterjuice", homepage: "http://letterjuice.cat/", tier: "okay" },
  { name: "Lettermatic", slug: "lettermatic", homepage: "https://lettermatic.com/", tier: "okay" },
  { name: "Lettermatic", slug: "lettermatic", homepage: "https://lettermatic.com/", tier: "okay" },
  { name: "Lettermin", slug: "lettermin", homepage: "https://lettermin.com/", tier: "okay" },
  { name: "LettError", slug: "letterror", homepage: "https://letterror.com/", tier: "best" },
  { name: "Letters from Sweden", slug: "letters-from-sweden", homepage: "https://lettersfromsweden.se/", tier: "okay" },
  { name: "Lettersetal", slug: "lettersetal", homepage: "https://lettersetal.co.uk/", tier: "okay" },
  { name: "Lettersoup", slug: "lettersoup", homepage: "https://www.lettersoup.de", tier: "okay" },
  { name: "Lewis McGuffie", slug: "lewis-mcguffie", homepage: "https://www.lewismcguffie.com/", tier: "okay" },
  { name: "Lift Type", slug: "lift-type", homepage: "https://www.lift-type.fr/", tier: "best" },
  { name: "limitype", slug: "limitype", homepage: "https://limitype.com/", tier: "notgood" },
  { name: "Lineto", slug: "lineto", homepage: "https://lineto.com/", tier: "best" },
  { name: "Linotype", slug: "linotype", homepage: "https://www.linotype.com/", tier: "okay" },
  { name: "lo-ol Type", slug: "lo-ol-type", homepage: "https://www.lo-ol.design/", tier: "okay" },
  { name: "London Type Foundry", slug: "london-type-foundry", homepage: "https://londontype.co.uk", tier: "okay" },
  { name: "Lost Type Co-op", slug: "lost-type-co-op", homepage: "http://www.losttype.com/", tier: "okay" },
  { name: "Love Letters", slug: "love-letters", homepage: "https://love-letters.fonts.xyz/", tier: "okay" },
  { name: "LucasFonts", slug: "lucasfonts", homepage: "https://www.lucasfonts.com/", tier: "best" },
  { name: "Ludwig", slug: "ludwig", homepage: "https://www.ludwigtype.de", tier: "okay" },
  { name: "Lund Design Co.", slug: "lund-design-co", homepage: "https://supply.family/", tier: "okay" },
  { name: "Luzi Type", slug: "luzi-type", homepage: "https://www.luzi-type.ch/", tier: "best" },
  { name: "Mai Type", slug: "mai-type", homepage: "https://www.maitype.xyz", tier: "okay" },
  { name: "Manic Type", slug: "manic-type", homepage: "https://www.manictype.com", tier: "okay" },
  { name: "Mark Simonson", slug: "mark-simonson", homepage: "https://www.marksimonson.com/", tier: "best" },
  { name: "Mark van Leeuwen", slug: "mark-van-leeuwen", homepage: "https://markvanleeuwen.nl/", tier: "okay" },
  { name: "Marmite de Fontes", slug: "marmite-defontes", homepage: "https://marmitedefontes.com/", tier: "okay" },
  { name: "Mass-Driver", slug: "mass-driver", homepage: "https://mass-driver.com/", tier: "okay" },
  { name: "Maxitype", slug: "maxitype", homepage: "https://maxitype.com/", tier: "best" },
  { name: "MB Type", slug: "mb-type", homepage: "https://mbtype.com", tier: "best" },
  { name: "MCKL", slug: "mckl", homepage: "https://mckltype.com", tier: "best" },
  { name: "McLetters", slug: "mcletters", homepage: "https://mcletters.co/", tier: "best" },
  { name: "Metis Foundry", slug: "metis-foundry", homepage: "http://metis-foundry.com", tier: "okay" },
  { name: "Milieu Grotesque", slug: "milieu-grotesque", homepage: "http://www.milieugrotesque.com/", tier: "okay" },
  { name: "Milieu Grotesque", slug: "milieu-grotesque", homepage: "https://www.myfonts.com/collections/milieu-grotesque", tier: "okay" },
  { name: "Milk Type Foundry", slug: "milk-type-foundry", homepage: "http://www.milktypefoundry.co.nz", tier: "okay" },
  { name: "Mint Type", slug: "mint-type", homepage: "https://minttype.com", tier: "okay" },
  { name: "Modern Type", slug: "modern-type", homepage: "https://www.modern-type.com", tier: "okay" },
  { name: "Mojomox", slug: "mojomox", homepage: "https://fonts.mojomox.com/", tier: "okay" },
  { name: "Monkey Type", slug: "monkey-type", homepage: "https://monkeytype.xyz/", tier: "okay" },
  { name: "Monkey Type", slug: "monkey-type", homepage: "https://mnkytype.com/", tier: "okay" },
  { name: "Monokrom", slug: "monokrom", homepage: "https://monokrom.no/", tier: "okay" },
  { name: "Moretype", slug: "moretype", homepage: "https://moretype.co.uk/", tier: "okay" },
  { name: "Morning Type", slug: "morning-type", homepage: "https://morningtype.com", tier: "okay" },
  { name: "Morula Type", slug: "morula-type", homepage: "https://morula-type.fonts.xyz/", tier: "best" },
  { name: "Mota Italic", slug: "mota-italic", homepage: "https://www.motaitalic.com", tier: "okay" },
  { name: "Muccatypo", slug: "muccatypo", homepage: "https://muccatypo.com", tier: "okay" },
  { name: "Muirmcneil", slug: "muirmcneil", homepage: "http://www.muirmcneil.com", tier: "okay" },
  { name: "Multiocular Type", slug: "multiocular-type", homepage: "https://www.multioculartype.co", tier: "okay" },
  { name: "MVB Fonts", slug: "mvb-fonts", homepage: "https://www.mvbfonts.com/", tier: "best" },
  { name: "Naipe Foundry", slug: "naipe-foundry", homepage: "https://store.naipefoundry.com", tier: "okay" },
  { name: "NaN", slug: "nan", homepage: "https://www.nan.xyz/", tier: "best" },
  { name: "Narrow Type", slug: "narrow-type", homepage: "https://www.narrowtype.com/", tier: "okay" },
  { name: "Ndiscover", slug: "ndiscover", homepage: "https://ndiscover.com", tier: "okay" },
  { name: "Neoflix Studio", slug: "neoflix-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "Netvarec Type", slug: "netvarec-type", homepage: "https://nctype.com/", tier: "okay" },
  { name: "Neubau", slug: "neubau", homepage: "https://neubauladen.com/", tier: "okay" },
  { name: "Newglyph", slug: "newglyph", homepage: "https://newglyph.com", tier: "okay" },
  { name: "Newlyn", slug: "newlyn", homepage: "https://newlyn.com/", tier: "best" },
  { name: "Nguyen Gobber", slug: "nguyen-gobber", homepage: "https://nguyengobber.com/", tier: "okay" },
  { name: "Nice To Type", slug: "nice-to-type", homepage: "https://nicetotype.de/", tier: "okay" },
  { name: "Nicolas Desle", slug: "nicolas-desle", homepage: "https://supply.family/", tier: "okay" },
  { name: "Nikolas Type", slug: "nikolas-type", homepage: "https://www.nikolastype.com/", tier: "okay" },
  { name: "NM Type", slug: "nm-type", homepage: "http://nmtype.com", tier: "okay" },
  { name: "Nodo Type Foundry", slug: "nodo-type-foundry", homepage: "https://nodotypefoundry.com/", tier: "okay" },
  { name: "Non Foundry", slug: "non-foundry", homepage: "https://nonfoundry.com/", tier: "best" },
  { name: "Nootype", slug: "nootype", homepage: "https://nootype.com/", tier: "okay" },
  { name: "Not Your Type", slug: "not-your-type", homepage: "https://notyourtype.nl", tier: "okay" },
  { name: "Nouvelle Noire", slug: "nouvelle-noire", homepage: "https://nouvellenoire.ch/", tier: "okay" },
  { name: "Nova Type Foundry", slug: "nova-type-foundry", homepage: "https://novatypefoundry.com", tier: "okay" },
  { name: "NovaraType", slug: "novaratype", homepage: "https://supply.family/", tier: "okay" },
  { name: "November", slug: "november", homepage: "https://www.nvmbr.in/", tier: "okay" },
  { name: "Nuform Type", slug: "nuform-type", homepage: "https://nuformtype.com/", tier: "okay" },
  { name: "Nymark Type", slug: "nymark-type", homepage: "https://www.nymarktype.co", tier: "okay" },
  { name: "Obrysy", slug: "obrysy", homepage: "https://obrysy.xyz/", tier: "best" },
  { name: "Occupant Fonts", slug: "occupant-fonts", homepage: "https://occupantfonts.com", tier: "best" },
  { name: "Off The Rack", slug: "off-the-rack", homepage: "https://supply.family/", tier: "okay" },
  { name: "Off Type", slug: "off-type", homepage: "https://off-type.com/", tier: "okay" },
  { name: "OGJ Type Design", slug: "ogj-type-design", homepage: "https://ogjtype.com/", tier: "okay" },
  { name: "OH no Type", slug: "oh-no-type", homepage: "https://ohnotype.co/", tier: "best" },
  { name: "Okay Type", slug: "okay-type", homepage: "http://okaytype.com", tier: "okay" },
  { name: "Oktnum Type Foundry", slug: "oktnum-type-foundry", homepage: "https://supply.family/", tier: "okay" },
  { name: "Old City Mailroom", slug: "old-city-mailroom", homepage: "https://www.oldcitymailroom.com/", tier: "okay" },
  { name: "Omnibus-Type", slug: "omnibus-type", homepage: "https://www.omnibus-type.com", tier: "okay" },
  { name: "Open Foundry", slug: "open-foundry", homepage: "https://open-foundry.com/", tier: "okay" },
  { name: "OPS Type", slug: "ops-type", homepage: "https://ops-type.com/", tier: "okay" },
  { name: "Optimo", slug: "optimo", homepage: "https://optimo.ch/", tier: "best" },
  { name: "Or Type", slug: "or-type", homepage: "https://ortype.is", tier: "best" },
  { name: "Order", slug: "order", homepage: "https://order.design/", tier: "okay" },
  { name: "Original Type", slug: "original-type", homepage: "https://originaltype.com", tier: "okay" },
  { name: "Otherwhere Collective", slug: "otherwhere-collective", homepage: "https://otherwherecollective.com", tier: "okay" },
  { name: "OTT Foundry", slug: "ott-foundry", homepage: "https://ott-foundry.com/", tier: "best" },
  { name: "Out of the Dark", slug: "out-of-the-dark", homepage: "https://www.outofthedark.swiss/", tier: "best" },
  { name: "Paavola Type", slug: "paavola-type", homepage: "https://www.paavolatype.com", tier: "okay" },
  { name: "Pampatype", slug: "pampatype", homepage: "https://pampatype.com", tier: "best" },
  { name: "Pangram Pangram Foundry", slug: "pangram-pangram-foundry", homepage: "https://pangrampangram.com/", tier: "best" },
  { name: "ParaType", slug: "paratype", homepage: "https://www.paratype.com/", tier: "best" },
  { name: "Patio Foundry", slug: "patio-foundry", homepage: "https://patiofoundry.com/", tier: "okay" },
  { name: "Peggo Fonts", slug: "peggo-fonts", homepage: "https://peggofonts.com", tier: "okay" },
  { name: "Peregrin Studio", slug: "peregrin-studio", homepage: "https://peregrinstudio.com/", tier: "okay" },
  { name: "PFA Typefaces", slug: "pfa-typefaces", homepage: "https://pfa-typefaces.com", tier: "okay" },
  { name: "Phantom Foundry", slug: "phantom-foundry", homepage: "http://phantom-foundry.com", tier: "okay" },
  { name: "Phil's Fonts", slug: "phils-fonts", homepage: "https://philsfonts.com/", tier: "notgood" },
  { name: "Philatype", slug: "philatype", homepage: "https://philatype.com/", tier: "okay" },
  { name: "Pixelbuddha", slug: "pixelbuddha", homepage: "https://supply.family/", tier: "okay" },
  { name: "Pizza Typefaces", slug: "pizza-typefaces", homepage: "https://typefaces.pizza/", tier: "okay" },
  { name: "Plain Form", slug: "plain-form", homepage: "https://plain-form.com/", tier: "okay" },
  { name: "Plau", slug: "plau", homepage: "https://plau.co/en/", tier: "okay" },
  { name: "Playtype", slug: "playtype", homepage: "https://playtype.com/", tier: "best" },
  { name: "Poem", slug: "poem", homepage: "https://www.poem-editions.com", tier: "okay" },
  { name: "Polytype", slug: "polytype", homepage: "https://polytype.co.uk/", tier: "okay" },
  { name: "Positype", slug: "positype", homepage: "https://positype.com", tier: "okay" },
  { name: "Power Type", slug: "power-type", homepage: "https://power-type.com/", tier: "best" },
  { name: "Praktypes", slug: "praktypes", homepage: "https://supply.family/", tier: "okay" },
  { name: "Pretend Foundry", slug: "pretend-foundry", homepage: "https://pretendfoundry.com", tier: "okay" },
  { name: "Primary Foundry", slug: "primary-foundry", homepage: "http://primary-foundry.com", tier: "okay" },
  { name: "Prioritype", slug: "prioritype", homepage: "https://prioritypeco.com/", tier: "best" },
  { name: "Process Type Foundry", slug: "process-type-foundry", homepage: "https://processtypefoundry.com/", tier: "okay" },
  { name: "Production Type", slug: "production-type", homepage: "https://www.productiontype.com/", tier: "best" },
  { name: "Prologue Type", slug: "prologue-type", homepage: "https://www.prologuetype.co", tier: "okay" },
  { name: "Proof of Words", slug: "proof-of-words", homepage: "https://proof-of-words.com", tier: "okay" },
  { name: "ProtoType Labs", slug: "prototype-labs", homepage: "https://supply.family/", tier: "okay" },
  { name: "PS Type Lab", slug: "ps-type-lab", homepage: "https://pstypelab.com", tier: "okay" },
  { name: "Public Type", slug: "public-type", homepage: "https://www.publictype.us", tier: "okay" },
  { name: "Pyte Foundry", slug: "pyte-foundry", homepage: "https://thepytefoundry.net", tier: "okay" },
  { name: "R-Typography", slug: "r-typography", homepage: "https://www.r-typography.com/", tier: "okay" },
  { name: "Radim Pesko", slug: "radim-pesko", homepage: "https://radimpesko.com/", tier: "okay" },
  { name: "Radim Pesko", slug: "radim-pesko", homepage: "https://radimpesko.com/", tier: "okay" },
  { name: "Radluka", slug: "radluka", homepage: "https://www.radluka.com", tier: "okay" },
  { name: "Ragamkata Studio", slug: "ragamkata-studio", homepage: "https://supply.family/", tier: "okay" },
  { name: "Rasmus Andersson", slug: "rasmus-andersson", homepage: "https://rsms.me/", tier: "best" },
  { name: "Razzia Type", slug: "razzia-type", homepage: "https://www.razziatype.com", tier: "okay" },
  { name: "Regular Bold Italic", slug: "regular-bold-italic", homepage: "https://regularbolditalic.com/", tier: "okay" },
  { name: "Regular Lines Type Foundry", slug: "regular-lines-type-foundry", homepage: "https://www.regularlines.com/", tier: "okay" },
  { name: "Rellence", slug: "rellence", homepage: "https://rellence.com/", tier: "okay" },
  { name: "Renegadefonts", slug: "renegadefonts", homepage: "https://www.renegadefonts.com/", tier: "okay" },
  { name: "Reset Type Studio", slug: "reset-type-studio", homepage: "https://reset-type.com/", tier: "okay" },
  { name: "Resistenza Type", slug: "resistenza-type", homepage: "https://www.resistenza.es/", tier: "okay" },
  { name: "RetroSupply Co.", slug: "retrosupply-co", homepage: "https://www.retrosupply.co/", tier: "okay" },
  { name: "Retype", slug: "retype", homepage: "https://www.re-type.com", tier: "okay" },
  { name: "Revolver Type Foundry", slug: "revolver-type-foundry", homepage: "https://www.revolvertype.com/", tier: "okay" },
  { name: "Riptype", slug: "riptype", homepage: "https://www.riptype.xyz", tier: "okay" },
  { name: "RNDI TYPE FOUNDRY", slug: "rndi-type-foundry", homepage: "https://supply.family/", tier: "okay" },
  { name: "Road to Venice Type", slug: "road-to-venice-type", homepage: "https://www.r-vtype.com", tier: "okay" },
  { name: "rooomspace creative lab", slug: "rooomspace-creative-lab", homepage: "https://supply.family/", tier: "okay" },
  { name: "Rosetta", slug: "rosetta", homepage: "https://rosettatype.com/", tier: "okay" },
  { name: "Rüdiger", slug: "rudiger", homepage: "https://rudiger.fonts.xyz/", tier: "best" },
  { name: "S6 Foundry", slug: "s6-foundry", homepage: "https://www.s6foundry.com/", tier: "okay" },
  { name: "Schick Toikka", slug: "schick-toikka", homepage: "https://www.schick-toikka.com/", tier: "best" },
  { name: "Schriftlabor", slug: "schriftlabor", homepage: "https://schriftlabor.at", tier: "okay" },
  { name: "Scifipoetry", slug: "scifipoetry", homepage: "https://scifipoetry.de", tier: "okay" },
  { name: "Sekyra Lab", slug: "sekyra-lab", homepage: "https://supply.family/", tier: "okay" },
  { name: "Serpentype", slug: "serpentype", homepage: "https://www.serpentype.com", tier: "okay" },
  { name: "Setup Type", slug: "setup-type", homepage: "https://www.setuptype.com", tier: "okay" },
  { name: "Sharp Type", slug: "sharp-type", homepage: "https://www.sharptype.co/", tier: "okay" },
  { name: "Signal", slug: "signal", homepage: "https://signalfoundry.com/", tier: "best" },
  { name: "SilverStag Type", slug: "silverstag-type", homepage: "https://silverstagtype.com/", tier: "okay" },
  { name: "Simple Bits", slug: "simple-bits", homepage: "https://simplebits.shop", tier: "okay" },
  { name: "Skilline Fonts Co.", slug: "skilline-fonts-co", homepage: "https://supply.family/", tier: "okay" },
  { name: "Slanted Hall", slug: "slanted-hall", homepage: "https://slantedhall.com/", tier: "okay" },
  { name: "SM", slug: "sm", homepage: "https://s-m.nu/", tier: "okay" },
  { name: "Smeltery", slug: "smeltery", homepage: "https://www.smeltery.net", tier: "okay" },
  { name: "Smuss Type Kiosk", slug: "smuss-type-kiosk", homepage: "https://typekiosk.smuss.studio/", tier: "okay" },
  { name: "Sociotype", slug: "sociotype", homepage: "https://socio-type.com/", tier: "best" },
  { name: "Softdrive Foundry", slug: "softdrive-foundry", homepage: "https://www.softdrivefoundry.com/", tier: "okay" },
  { name: "Softulka", slug: "softulka", homepage: "https://supply.family/", tier: "okay" },
  { name: "Source Type", slug: "source-type", homepage: "https://www.sourcetype.com/", tier: "best" },
  { name: "Souvenir Typefaces", slug: "souvenir-typefaces", homepage: "https://souvenirtypefaces.xyz/", tier: "best" },
  { name: "Spaghetype", slug: "spaghetype", homepage: "https://www.spaghetype.com", tier: "okay" },
  { name: "Standard Type Foundry", slug: "standard-type-foundry", homepage: "https://www.standardtypefoundry.com", tier: "okay" },
  { name: "Store Norske Skriftkompani", slug: "store-norske-skriftkompani", homepage: "https://skriftkompani.no/", tier: "okay" },
  { name: "Storm Type Foundry", slug: "storm-type", homepage: "https://www.stormtype.com/", tier: "best" },
  { name: "Studio Feixen Fonts", slug: "studio-feixen-fonts", homepage: "https://fonts.studiofeixen.ch/", tier: "okay" },
  { name: "Studio Few", slug: "studio-few", homepage: "https://supply.family/", tier: "okay" },
  { name: "Studio Rene Bieder", slug: "studio-rene-bieder", homepage: "https://www.renebieder.com/", tier: "best" },
  { name: "Studio Sascha Bente", slug: "studio-sascha-bente", homepage: "https://saschabente.com/", tier: "okay" },
  { name: "Studio Triple", slug: "studio-triple", homepage: "https://studiotriple.fr/", tier: "okay" },
  { name: "Sudtipos", slug: "sudtipos", homepage: "https://sudtipos.com/", tier: "best" },
  { name: "Suitcase Type Foundry", slug: "suitcase-type", homepage: "https://www.suitcasetype.com/", tier: "okay" },
  { name: "Supercontinente", slug: "supercontinente", homepage: "https://supercontinente.com/", tier: "okay" },
  { name: "Superior Type", slug: "superior-type", homepage: "https://superiortype.com/", tier: "okay" },
  { name: "Supernulla", slug: "supernulla", homepage: "https://supply.family/", tier: "okay" },
  { name: "Supertype", slug: "supertype", homepage: "https://supertype.de/", tier: "okay" },
  { name: "SWIM Type", slug: "swim-type", homepage: "https://supply.family/", tier: "okay" },
  { name: "Swiss Typefaces", slug: "swiss-typefaces", homepage: "https://www.swisstypefaces.com/", tier: "best" },
  { name: "Synthview", slug: "synthview", homepage: "https://typography.synthview.com/", tier: "okay" },
  { name: "Tandem Type", slug: "tandem-type", homepage: "https://www.tandemtype.co", tier: "okay" },
  { name: "Taylor Penton", slug: "taylor-penton", homepage: "https://www.taylorpenton.com/", tier: "best" },
  { name: "Teaser", slug: "teaser", homepage: "https://teaser.fonts.xyz/", tier: "notgood" },
  { name: "Teeline Fonts", slug: "teeline-fonts", homepage: "https://teelinefonts.com", tier: "okay" },
  { name: "Tegamitype", slug: "tegamitype", homepage: "https://tegamitype.com", tier: "okay" },
  { name: "Terminal Design", slug: "terminal-design", homepage: "https://www.terminaldesign.com/", tier: "okay" },
  { name: "That That Type", slug: "that-that-type", homepage: "https://thatthattype.com/", tier: "okay" },
  { name: "The Designers Foundry", slug: "the-designers-foundry", homepage: "https://thedesignersfoundry.com/", tier: "best" },
  { name: "The Foundry Types", slug: "the-foundry-types", homepage: "https://www.thefoundrytypes.com/", tier: "okay" },
  { name: "The League of Moveable Type", slug: "the-league-of-moveable-type", homepage: "https://www.theleagueofmoveabletype.com/", tier: "okay" },
  { name: "The Letters", slug: "the-letters", homepage: "https://theletters.co/", tier: "okay" },
  { name: "The Native Saint Club", slug: "the-native-saint-club", homepage: "https://supply.family/", tier: "okay" },
  { name: "The Northern Block", slug: "the-northern-block", homepage: "https://www.thenorthernblock.co.uk/", tier: "best" },
  { name: "The Temporary State", slug: "the-temporary-state", homepage: "https://type.tmpstate.net/", tier: "okay" },
  { name: "Threedotstype", slug: "threedotstype", homepage: "https://threedotstype.com/", tier: "best" },
  { name: "Tightype", slug: "tightype", homepage: "https://tightype.com/", tier: "okay" },
  { name: "Tiny Type Co.", slug: "tiny-type-co", homepage: "https://tinytype.co", tier: "okay" },
  { name: "Tipofili", slug: "tipofili", homepage: "https://tipofili.com", tier: "okay" },
  { name: "Tipografies", slug: "tipografies", homepage: "https://tipografies.com", tier: "okay" },
  { name: "Tipotype", slug: "tipotype", homepage: "http://tipotype.com", tier: "okay" },
  { name: "Tiro Typeworks", slug: "tiro-typeworks", homepage: "https://www.tiro.com", tier: "best" },
  { name: "TØ—Labs™", slug: "to-labs", homepage: "https://supply.family/", tier: "okay" },
  { name: "Tofu Type", slug: "tofu-type", homepage: "https://tofutype.ca/", tier: "best" },
  { name: "Tokotype", slug: "tokotype", homepage: "https://www.tokotype.com/", tier: "okay" },
  { name: "Tour de Force", slug: "tour-de-force", homepage: "https://tourdefonts.com", tier: "okay" },
  { name: "Troisième Type", slug: "troisieme-type", homepage: "https://troisieme-type.com/", tier: "okay" },
  { name: "Tropical Type", slug: "tropical-type", homepage: "https://tropicaltype.com/", tier: "okay" },
  { name: "TrueType", slug: "truetype", homepage: "https://supply.family/", tier: "okay" },
  { name: "Trulytype", slug: "trulytype", homepage: "https://trulytype.com", tier: "okay" },
  { name: "Tunera", slug: "tunera", homepage: "https://www.tunera.xyz/", tier: "okay" },
  { name: "Tüpokompanii", slug: "tupokompanii", homepage: "https://tupokompanii.com/", tier: "okay" },
  { name: "TYPE BY", slug: "type-by", homepage: "https://www.typeby.com/", tier: "okay" },
  { name: "Type Culture", slug: "type-culture", homepage: "https://typeculture.com", tier: "okay" },
  { name: "Type Department", slug: "type-department", homepage: "https://type-department.com/", tier: "okay" },
  { name: "Type Different", slug: "type-different", homepage: "https://www.typedifferent.com", tier: "okay" },
  { name: "Type Forward", slug: "type-forward", homepage: "https://www.typeforward.com/", tier: "okay" },
  { name: "Type Mania", slug: "type-mania", homepage: "https://supply.family/", tier: "okay" },
  { name: "Type of Feeling", slug: "type-of-feeling", homepage: "https://typeoffeeling.com/", tier: "best" },
  { name: "Type Salon", slug: "type-salon", homepage: "https://type-salon.com", tier: "okay" },
  { name: "Type-ø-tones", slug: "type-o-tones", homepage: "http://type-o-tones.com", tier: "okay" },
  { name: "type.today", slug: "type-today", homepage: "https://type.today/en", tier: "okay" },
  { name: "Typearture", slug: "typearture", homepage: "https://www.typearture.com", tier: "okay" },
  { name: "Typeheist", slug: "typeheist", homepage: "https://typeheist.co", tier: "okay" },
  { name: "Typeji", slug: "typeji", homepage: "https://typeji.com/", tier: "okay" },
  { name: "Typejockeys", slug: "typejockeys", homepage: "https://www.typejockeys.com", tier: "okay" },
  { name: "Typeland", slug: "typeland", homepage: "https://type.land", tier: "okay" },
  { name: "Typemanufactur", slug: "typemanufactur", homepage: "https://www.typemanufactur.com/en", tier: "okay" },
  { name: "TypeMates", slug: "typemates", homepage: "https://www.typemates.com/", tier: "okay" },
  { name: "Typeóca", slug: "typeoca", homepage: "https://typeoca.com/", tier: "okay" },
  { name: "Typeparties", slug: "typeparties", homepage: "https://supply.family/", tier: "okay" },
  { name: "Typerepublic", slug: "typerepublic", homepage: "https://typerepublic.com", tier: "okay" },
  { name: "Typespec", slug: "typespec", homepage: "https://typespec.co.uk/", tier: "best" },
  { name: "TypeThis!Studio", slug: "typethis-studio", homepage: "https://www.typethis.studio/", tier: "okay" },
  { name: "TypeTogether", slug: "type-together", homepage: "https://www.type-together.com/", tier: "okay" },
  { name: "TypeTogether", slug: "type-together", homepage: "https://www.type-together.com/", tier: "best" },
  { name: "TypeType", slug: "type-type", homepage: "https://typetype.org/", tier: "okay" },
  { name: "Typeverything", slug: "typeverything", homepage: "https://typeverything.com/", tier: "okay" },
  { name: "TypoBureau", slug: "typobureau", homepage: "https://supply.family/", tier: "okay" },
  { name: "Typocalypse", slug: "typocalypse", homepage: "http://www.typocalypse.com", tier: "okay" },
  { name: "Typofonderie", slug: "typofonderie", homepage: "https://typofonderie.com/", tier: "best" },
  { name: "Typographies.fr", slug: "typographies-fr", homepage: "http://typographies.fr/", tier: "okay" },
  { name: "Typotheque", slug: "typotheque", homepage: "https://www.typotheque.com/", tier: "best" },
  { name: "Typozon", slug: "typozon", homepage: "https://typozon.xyz/", tier: "okay" },
  { name: "U.S. Graphics Company", slug: "u-s-graphics-company", homepage: "https://usgraphics.com/", tier: "okay" },
  { name: "U+270D", slug: "u270d", homepage: "https://u270d.eesab.fr/", tier: "okay" },
  { name: "Ultra Kuhl", slug: "ultra-kuhl", homepage: "https://ultra-kuhl.com/", tier: "best" },
  { name: "Uncut", slug: "uncut", homepage: "https://uncut.wtf/", tier: "okay" },
  { name: "Undercase", slug: "undercase", homepage: "https://undercase.xyz/", tier: "okay" },
  { name: "Underscore Type", slug: "underscore-type", homepage: "https://underscoretype.com/", tier: "okay" },
  { name: "Underware", slug: "underware", homepage: "https://www.underware.nl", tier: "best" },
  { name: "Undt", slug: "undt", homepage: "https://undt.fonts.xyz/", tier: "okay" },
  { name: "Unio Designs", slug: "unio-designs", homepage: "https://supply.family/", tier: "okay" },
  { name: "Ursa Minor", slug: "ursa-minor", homepage: "https://ursaminor.xyz", tier: "okay" },
  { name: "URW Type Foundry", slug: "urw-type-foundry", homepage: "https://www.urwtype.com/", tier: "okay" },
  { name: "Vectro", slug: "vectro", homepage: "https://www.vectrotype.com/", tier: "okay" },
  { name: "Velvetyne", slug: "velvetyne", homepage: "https://velvetyne.fr/", tier: "okay" },
  { name: "Very Cool Studio", slug: "very-cool-studio", homepage: "https://verycoolstudio.com/", tier: "okay" },
  { name: "Vibrant Types", slug: "vibrant-types", homepage: "https://www.vibrant-types.com/", tier: "okay" },
  { name: "Victoria Rushton", slug: "victoria-rushton", homepage: "https://victoriarushton.com", tier: "okay" },
  { name: "Village", slug: "village", homepage: "https://vllg.com/", tier: "okay" },
  { name: "VJ Type", slug: "vj-type", homepage: "https://vj-type.com/", tier: "best" },
  { name: "Vocal Type", slug: "vocal-type", homepage: "https://www.vocaltype.co/", tier: "okay" },
  { name: "W Type Foundry", slug: "w-type-foundry", homepage: "https://wtypefoundry.com", tier: "okay" },
  { name: "Wabi Sabi Type", slug: "wabi-sabi-type", homepage: "https://wabisabitypeshop.com/", tier: "okay" },
  { name: "Walden Font Co.", slug: "walden-font-co", homepage: "https://www.waldenfont.com", tier: "okay" },
  { name: "We Love Fonts", slug: "we-love-fonts", homepage: "https://we-love-fonts.fonts.xyz/", tier: "notgood" },
  { name: "Weekend Type", slug: "weekend-type", homepage: "https://weekendtype.xyz/", tier: "okay" },
  { name: "WELTKERN", slug: "weltkern", homepage: "https://www.weltkern.com/", tier: "okay" },
  { name: "WiseType", slug: "wisetype", homepage: "https://wisetype.nl/", tier: "okay" },
  { name: "Workhorse Type Foundry", slug: "workhorse-type-foundry", homepage: "https://workhorsetypefoundry.com", tier: "okay" },
  { name: "Writtenshape", slug: "writtenshape", homepage: "https://www.writtenshape.com", tier: "okay" },
  { name: "X Cicéro", slug: "x-cicero", homepage: "https://xcicero.esad-gv.net/", tier: "okay" },
  { name: "XO Type Co", slug: "xo-type-co", homepage: "https://xotype.co", tier: "okay" },
  { name: "XYZ Type", slug: "xyz-type", homepage: "https://xyztype.com/", tier: "okay" },
  { name: "yasireknc", slug: "yasireknc", homepage: "https://supply.family/", tier: "okay" },
  { name: "Yeahright Type", slug: "yeahright-type", homepage: "https://yeahrighttype.com/", tier: "okay" },
  { name: "Yenty Jap Co", slug: "yenty-jap-co", homepage: "https://supply.family/", tier: "okay" },
  { name: "Yep! Type Foundry", slug: "yep-type-foundry", homepage: "https://yeptype.com", tier: "okay" },
  { name: "Zarma Type", slug: "zarma-type", homepage: "https://zarmatype.com/", tier: "notgood" },
  { name: "Zetafonts", slug: "zetafonts", homepage: "https://www.zetafonts.com/", tier: "okay" },
];

// Foundries confirmed unscrapable — JS-rendered, bot-blocked, or no listing page.
// domain matches foundries.json domain field.
export const BLOCKED_FOUNDRIES: { domain: string; name: string; reason: string }[] = [
  { domain: "supply.family", name: "Zarma Type", reason: "reseller aggregator, not a single foundry page" },
  { domain: "studioplums.com", name: "Ian Adjeidu", reason: "portfolio site, no listing page" },
  { domain: "experim-etal.lettersetal.co.uk", name: "Lettersetal", reason: "JS-rendered" },
  { domain: "limitype.com", name: "Limitype", reason: "JS-rendered, no crawlable listing" },
  { domain: "typokompanii.com", name: "Tüpokompanii", reason: "JS-rendered" },
  { domain: "behance.net", name: "Rajesh Rajput", reason: "Behance portfolio, not indexable" },
  { domain: "castletype.com", name: "Castle Type", reason: "old static site, no structured listing" },
  { domain: "youworkforthem.com", name: "YouWorkForThem", reason: "reseller marketplace, not a foundry" },
  { domain: "paratype.com", name: "Paratype", reason: "large catalogue, no structured listing page" },
  { domain: "colophon-foundry.org", name: "Colophon", reason: "Redirects to MyFonts; original domain no longer has a catalogue" },
  { domain: "contemporarytype.com", name: "Contemporary Type", reason: "reseller, JS-rendered listing with no crawlable font links" },
  { domain: "vllg.com", name: "Village", reason: "React SPA, no crawlable listing" },
  { domain: "205.tf", name: "205TF", reason: "Next.js SPA, no crawlable listing" },
  { domain: "monkeytype.xyz", name: "Monkey Type", reason: "SPA, no crawlable listing" },
  { domain: "ultra-kuhl.com", name: "Ultra Kuhl", reason: "rebranded as Rellence, site unreachable" },
  { domain: "commercialclassics.com", name: "Commercial Classics", reason: "SSL certificate expired" },
  { domain: "milieugrotesque.com", name: "Milieu Grotesque", reason: "redirects to MyFonts, no own listing" },
  // Batch 18 additions
  { domain: "futurefonts.xyz", name: "Future Fonts", reason: "beta marketplace aggregator, not a single foundry" },
  { domain: "typenetwork.com", name: "TypeNetwork", reason: "reseller platform, not a foundry" },
  { domain: "fontbureau.typenetwork.com", name: "Font Bureau on TypeNetwork", reason: "hosted on TypeNetwork reseller platform" },
  { domain: "monotype.com", name: "Monotype", reason: "corporate conglomerate, not an independent foundry" },
  { domain: "fonthaus.com", name: "FontHaus", reason: "reseller aggregator" },
  { domain: "fonts.ilovetypography.com", name: "ILoveTypography Fonts", reason: "aggregator storefront, not a foundry" },
  { domain: "fontsquirrel.com", name: "FontSquirrel", reason: "free fonts aggregator, not a foundry" },
  { domain: "dstype.com", name: "DSType Foundry", reason: "notgood tier — quality not up to index standard" },
  { domain: "emigre.com", name: "Emigre", reason: "notgood tier — legacy catalogue, no structured listing" },
  { domain: "p22.com", name: "P22 Type Foundry", reason: "notgood tier" },
  { domain: "sharptype.co", name: "Sharp Type", reason: "notgood tier" },
  { domain: "velvetyne.fr", name: "VTF (Velvetyne)", reason: "notgood tier" },
  { domain: "letterheadfonts.com", name: "Letterhead Fonts", reason: "notgood tier" },
  { domain: "hbtype.com", name: "HB Type", reason: "loose tier" },
  { domain: "badtype.club", name: "Bad Type Club", reason: "loose tier" },
  { domain: "atypical.gr", name: "ATYPICAL", reason: "loose tier" },
  { domain: "entravaux.framer.website", name: "En Travaux", reason: "notgood tier" },
  { domain: "overlaptype.com", name: "Overlap Type", reason: "notgood tier" },
  { domain: "undercase.xyz", name: "Undercase Type", reason: "notgood tier" },
  { domain: "heritagetype.com", name: "Heritage Type Co.", reason: "notgood tier" },
  { domain: "psyops.com", name: "PSY/OPS Type Foundry", reason: "notgood tier" },
  { domain: "motyfo.com", name: "MoTyFo", reason: "notgood tier" },
  { domain: "heytype.xyz", name: "Hey", reason: "notgood tier" },
  { domain: "joliciatype.com", name: "Joliciatype", reason: "notgood tier" },
  { domain: "exljbris.com", name: "exljbris", reason: "notgood tier" },
  { domain: "sun.fo", name: "Sun", reason: "notgood tier" },
  { domain: "rsztype.com", name: "Resistenza Type", reason: "notgood tier" },
  { domain: "jamesplattner.com", name: "James Plattner Studio", reason: "lettering/logo portfolio, not a type foundry" },
  { domain: "degarism.com", name: "degarism", reason: "coming soon, no live catalogue" },
  { domain: "berzulis.com", name: "Beržulis", reason: "site down" },
  { domain: "supercontinente.com", name: "Supercontinente", reason: "loose tier" },
  { domain: "folchstudio.com", name: "FOLCH Studio", reason: "agency site; fonts at fontsfromfolch.com (already indexed)" },
  { domain: "silverstag.design", name: "SilverStag (old domain)", reason: "redirects to silverstagtype.com which is already registered" },
  { domain: "type-01.com", name: "TYPE01", reason: "editorial/blog site, not a type foundry storefront" },
  { domain: "fonts.gr", name: "Fonts.gr", reason: "Greek aggregator site" },
  { domain: "t26.com", name: "T.26", reason: "sells individual font weight packs rather than typeface families; structure too granular" },
  { domain: "ultra-kuhl.com", name: "Ultra Kuhl", reason: "domain expired and hijacked; site dead" },
  { domain: "milieugrotesque.com", name: "Milieu Grotesque", reason: "domain redirects to MyFonts; foundry site gone" },
  { domain: "vllg.com", name: "Village", reason: "vllg.com permanently redirects to laborandwait.xyz; indexed separately as Labor and Wait" },
  { domain: "typefriends.com", name: "Riegla & Riegraf", reason: "Readymag subscription expired; site dead" },
  { domain: "uxumuxum.com", name: "Uxum", reason: "React SPA, single-product site — not a foundry catalogue" },
  { domain: "fontsfromfolch.com", name: "Fonts from Folch", reason: "single-page site; no individual typeface pages to index" },
  { domain: "authentic.website", name: "Authentic", reason: "shop closed" },
  { domain: "studio2am.co", name: "Studio 2AM", reason: "unverified — needs scouting" },
  { domain: "ui8.net", name: "UI8", reason: "design asset marketplace, not a type foundry" },
  { domain: "corp.gmarket.com", name: "G마켓", reason: "Korean e-commerce site, not a type foundry" },
  { domain: "design-research.be", name: "LIBRE FONTS BY WOMXN", reason: "curated resource list, not a foundry" },
  { domain: "dutypefoundry.com", name: "Dutype", reason: "unverified — needs scouting" },
  { domain: "typefaces.temporarystate.net", name: "The Temporary State (old domain)", reason: "foundry moved to type.tmpstate.net; already registered and indexed" },
];

export function getFoundryBySlug(slug: string): FoundryInfo | undefined {
  return FOUNDRIES.find((f) => f.slug === slug);
}

export function getFoundryByName(name: string): FoundryInfo | undefined {
  return FOUNDRIES.find((f) => f.name === name);
}
